---
# We need to fetch the secret from the MANAGED cluster using its kubeconfig.
- name: "Fetch Service Account Token Secret for {{ cluster_item.name }}"
  kubernetes.core.k8s_info:
    kubeconfig: "./kubeconfig_{{ cluster_item.name }}"
    kind: Secret
    name: "ansible-token"
    namespace: "default"
  register: sa_token_secret

- name: "Fail if Token Secret not found"
  fail:
    msg: "Could not find 'ansible-token' secret on cluster {{ cluster_item.name }}"
  when: sa_token_secret.resources | length == 0

- name: "Get Cluster API URL from Kubeconfig"
  set_fact:
    _cluster_url: "{{ (lookup('file', './kubeconfig_' + cluster_item.name) | from_yaml).clusters[0].cluster.server }}"

- name: "Set Credentials Facts for {{ cluster_item.name }}"
  set_fact:
    "{{ cluster_item.name }}_url": "{{ _cluster_url }}"
    "{{ cluster_item.name }}_token": "{{ sa_token_secret.resources[0].data.token | b64decode }}"
    "{{ cluster_item.name }}_ca_cert": "{{ sa_token_secret.resources[0].data['ca.crt'] }}" # Base64 encoded for ArgoCD

- name: "Debug Fetched Token"
  debug:
    msg: "Token for {{ cluster_item.name }} is set. Length: {{ (lookup('vars', cluster_item.name + '_token') | length) }}"

