- name: Export and Clean Kubernetes Resources for a VM
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    # --- Git Configuration ---
    git_ssh_key_path: "{{ lookup('env', 'ANSIBLE_PRIVATE_KEY_FILE') }}"
    github_user: "kseremet"
    repo_name: "gitops-vm-dr-manifests"
    repo_fqdn: "github.com"
    repo_url: "git@github.com:{{ github_user }}/{{ repo_name }}.git" # SSH URL

    # --- Kustomize Configuration ---
    target_cluster_name: cls2

  tasks:
    - name: Create a unique temporary directory for the Git clone
      ansible.builtin.tempfile:
        state: directory
        prefix: "gitops_dr_event_processor_"
      register: temp_clone_dir

    - name: Set clone_dir fact
      ansible.builtin.set_fact:
        clone_dir: "{{ temp_clone_dir.path }}"

    - name: Perform a shallow clone of the Git repository via SSH
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ clone_dir }}"
        depth: 1
        clone: true
        update: true
        key_file: "{{ git_ssh_key_path }}"
        accept_hostkey: true

    - name: Initialize the global Git repository structure
      ansible.builtin.include_tasks:
        file: tasks/initialize_git_repo.yaml

    - name: Process each VM from the batch
      ansible.builtin.include_tasks:
        file: tasks/process_vm_from_batch.yml
      loop: "{{ vm_objects_list }}"
      loop_control:
        loop_var: "event_vm_object"

    - name: Commit and push all reconciliation changes
      ansible.builtin.include_tasks:
        file: tasks/git_commit_push.yaml
      vars:
        commit_message: "Event-Driven VM DR sync"

    - name: Clean up the temporary clone directory
      ansible.builtin.file:
        path: "{{ clone_dir }}"
        state: absent
      when: clone_dir is defined
