- name: Reconcile all DR-enabled VMs and sync to Git
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    # --- Git Configuration ---
    git_ssh_key_path: "{{ lookup('env', 'ANSIBLE_PRIVATE_KEY_FILE') }}"
    github_user: "kseremet"
    repo_name: "gitops-vm-dr-manifests"
    repo_url: "git@github.com:{{ github_user }}/{{ repo_name }}.git" # SSH URL

    # --- Kustomize Configuration ---
    target_cluster_name: cls2

  tasks:
    - name: Create a unique temporary directory for the Git clone
      ansible.builtin.tempfile:
        state: directory
        prefix: "gitops_dr_reconciler_"
      register: temp_clone_dir

    - name: Set clone_dir fact
      ansible.builtin.set_fact:
        clone_dir: "{{ temp_clone_dir.path }}"

    - name: Get all DR-enabled VMs from the entire cluster
      kubernetes.core.k8s_info:
        kind: VirtualMachine
        api_version: kubevirt.io/v1
        label_selectors:
          - "dr.demojam.com/enabled=true"
      register: vm_discovery_results

    - name: Exit if no VMs are found to process
      ansible.builtin.meta: end_play
      when: vm_discovery_results.resources | length == 0

    - name: Perform a shallow clone of the Git repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ clone_dir }}"
        depth: 1
        clone: true
        update: true
        key_file: "{{ git_ssh_key_path }}"
        accept_hostkey: true

    - name: Initialize the global Git repository structure
      ansible.builtin.include_tasks:
        file: tasks/initialize_git_repo.yaml

    - name: Process each discovered VM
      ansible.builtin.include_tasks:
        file: tasks/process_single_vm.yml
      loop: "{{ vm_discovery_results.resources }}"
      loop_control:
        loop_var: vm_object
        label: "{{ vm_object.metadata.namespace }}/{{ vm_object.metadata.name }}"

    - name: Commit and push all reconciliation changes
      ansible.builtin.include_tasks:
        file: tasks/git_commit_push.yaml
      vars:
        commit_message: "Automated DR Reconciliation Sync"