- name: Check for any changes in the repository
  ansible.builtin.command: git status --porcelain
  args:
    chdir: "{{ clone_dir }}"
  register: git_status
  changed_when: git_status.stdout | length > 0

- name: Commit and push all changes if any were made
  when: git_status.changed
  block:
    - name: Add all changes to git staging
      ansible.builtin.command: git add .
      args:
        chdir: "{{ clone_dir }}"

    - name: Commit changes
      ansible.builtin.command: "git commit -m '{{ commit_message | default('Automated Git Sync') }}'"
      args:
        chdir: "{{ clone_dir }}"

    - name: Push changes to the remote repository
      ansible.builtin.command: git push origin HEAD
      args:
        chdir: "{{ clone_dir }}"
      environment:
            GIT_SSH_COMMAND: "ssh -i {{ git_ssh_key_path }} -o StrictHostKeyChecking=no"
