- name: Check for any changes in the repository
  ansible.builtin.command: git status --porcelain
  args:
    chdir: "{{ clone_dir }}"
  register: git_status
  changed_when: git_status.stdout | length > 0

- name: Commit and push all changes if any were made
  when: git_status.changed
  block:
    - name: Add all changes to git staging
      ansible.builtin.command: git add .
      args:
        chdir: "{{ clone_dir }}"

    - name: Set git user email for commit
      ansible.builtin.command: "git config --local user.email '{{ git_commit_email | default('aap-bot@example.com') }}'"
      args:
        chdir: "{{ clone_dir }}"
      changed_when: false

    - name: Set git user name for commit
      ansible.builtin.command: "git config --local user.name '{{ git_commit_username | default('AAP Automation Bot') }}'"
      args:
        chdir: "{{ clone_dir }}"

    - name: Commit changes
      ansible.builtin.command: "git commit -m '{{ commit_message | default('Automated Git Sync') }}'"
      args:
        chdir: "{{ clone_dir }}"

    - name: Push changes to the remote repository
      ansible.builtin.command: git push origin HEAD
      args:
        chdir: "{{ clone_dir }}"
